# spell-checker: ignore androideabi taiki binutils riscv dtolnay pipefail armv gungraun destdir
# spell-checker: ignore cachegrind memcheck
name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build artifacts
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
        valgrind:
          - "3.26.0"
          - "3.25.1"
          - "3.25.0"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install prerequisites
        run: ./prepare.sh
      - name: Build valgrind
        run: ./build_valgrind.sh ${{ matrix.valgrind }}
      - name: Install valgrind
        run: |
          cd build/valgrind-"${{ matrix.valgrind }}"
          sudo make -j"$(nproc)" install
      - name: Run and test valgrind
        run: |
          /usr/bin/valgrind --tool=cachegrind ls -la
          /usr/bin/valgrind --tool=memcheck ls -la
