# spell-checker: ignore androideabi taiki binutils riscv dtolnay pipefail armv gungraun destdir
# spell-checker: ignore realpath
name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+-[0-9]+"]

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create a draft release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get the release version from the tag
        run: echo "VERSION=${{ github.ref_name }}" >> "$GITHUB_ENV"
      - name: Create release if it does not exist
        run: |
          if ! gh release view "$VERSION" &>/dev/null; then
            gh release create "$VERSION" --draft --verify-tag --title "$VERSION" -F CHANGELOG.md
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: ${{ env.VERSION }}

  build_linux:
    name: Build artifacts
    needs: ["release"]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
        valgrind:
          - "3.23.0"
          - "3.24.0"
          - "3.25.0"
          - "3.25.1"
          - "3.26.0"
          - "3.27.0"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Prepare
        run: |
          mkdir -p build/root build/archive

          build_output="$(realpath build/root)"
          archive_dir="$(realpath build/archive)"
          archive_name="valgrind-${{ matrix.valgrind }}-x86_64-${{ matrix.os }}.tar.gz"
          archive_sum="${archive_name}.sha256"

          {
            echo "BUILD_OUTPUT=${build_output}"
            echo "ARCHIVE_DIR=${archive_dir}"
            echo "ARCHIVE_NAME=${archive_name}"
            echo "ARCHIVE_SUM=${archive_sum}"
          } >> "$GITHUB_ENV"
      - name: Check if archive already exists
        run: |
          set -o pipefail

          if gh release view ${{ needs.release.outputs.version }} --json assets | jq -e --arg name "${{ env.ARCHIVE_NAME }}" '.assets[] | select(.name == $name)'; then
            echo "Check: archive '${{ env.ARCHIVE_NAME }}' already exists for this version '${{ needs.release.outputs.version }}'"
            echo "CHECK=failure" >> $GITHUB_ENV
          else
            echo "CHECK=success" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install prerequisites
        if: env.CHECK == 'success'
        run: ./prepare.sh
      - name: Build valgrind
        if: env.CHECK == 'success'
        run: ./build_valgrind.sh ${{ matrix.valgrind }}
      - name: Create archive
        if: env.CHECK == 'success'
        run: |
          set -eux

          build_output="${{ env.BUILD_OUTPUT }}"
          archive_dir="${{ env.ARCHIVE_DIR }}"
          archive_name="${{ env.ARCHIVE_NAME }}"
          archive_sum="${{ env.ARCHIVE_SUM }}"

          cd build/valgrind-"${{ matrix.valgrind }}"
          make -j"$(nproc)" install BUILD_DOCS=none DESTDIR="${build_output}"

          rm -rvf "${build_output}/usr/share/"{man,doc}

          cd "${archive_dir}"
          tar czf "${archive_name}" -C "${build_output}" usr/
          sha256sum "$archive_name" > "$archive_sum"

          du -h "${archive_name}"
          tar tzf "${archive_name}"
      - name: Upload archive
        if: env.CHECK == 'success'
        run: gh release upload "${{ needs.release.outputs.version }}" "${{ env.ARCHIVE_NAME }}" "${{ env.ARCHIVE_SUM }}"
        working-directory: "${{ env.ARCHIVE_DIR }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_freebsd:
    name: Build artifacts
    needs: ["release"]
    strategy:
      fail-fast: false
      matrix:
        freebsd:
          - "14.0"
          - "14.1"
          - "14.2"
          - "14.3"
          - "15.0"
        valgrind:
          - "3.23.0"
          - "3.24.0"
          - "3.25.0"
          - "3.25.1"
          - "3.26.0"
          - "3.27.0"

        exclude:
          - freebsd: "15.0"
            valgrind: "3.23.0"
          - freebsd: "15.0"
            valgrind: "3.24.0"
          - freebsd: "15.0"
            valgrind: "3.25.0"
          - freebsd: "15.0"
            valgrind: "3.25.1"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Prepare
        run: |
          archive_name="valgrind-${{ matrix.valgrind }}-x86_64-freebsd-${{ matrix.freebsd }}.tar.gz"
          archive_sum="${archive_name}.sha256"

          {
            echo "ARCHIVE_NAME=${archive_name}"
            echo "ARCHIVE_SUM=${archive_sum}"
          } >> "$GITHUB_ENV"
      - name: Check if archive already exists
        run: |
          set -o pipefail

          if gh release view ${{ needs.release.outputs.version }} --json assets | jq -e --arg name "${{ env.ARCHIVE_NAME }}" '.assets[] | select(.name == $name)'; then
            echo "Check: archive '${{ env.ARCHIVE_NAME }}' already exists for this version '${{ needs.release.outputs.version }}'"
            echo "CHECK=failure" >> $GITHUB_ENV
          else
            echo "CHECK=success" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: cross-platform-actions/action@v0.32.0
        if: env.CHECK == 'success'
        env:
          ARCHIVE_NAME: ${{ env.ARCHIVE_NAME }}
          ARCHIVE_SUM: ${{ env.ARCHIVE_SUM }}
        with:
          environment_variables: ARCHIVE_NAME ARCHIVE_SUM
          operating_system: freebsd
          architecture: x86-64
          version: ${{ matrix.freebsd }}
          shell: bash
          memory: 8G
          cpu_count: 4
          sync_files: "true"
          run: |
            set -eux

            # Install prerequisites
            sudo pkg install -y wget autoconf automake gcc git bzip2 gmake

            ./build_valgrind.sh "${{ matrix.valgrind }}" "freebsd"

            mkdir -p 'archive' 'build/root'
            build_output="$(realpath build/root)"
            archive_dir="$(realpath archive)"

            cd build/valgrind-"${{ matrix.valgrind }}"
            gmake -j"$(nproc)" install BUILD_DOCS=none DESTDIR="${build_output}"

            rm -rvf "${build_output}/usr/local/share/"{man,doc}

            cd "${archive_dir}"
            tar czf "${ARCHIVE_NAME}" -C "${build_output}" usr/
            sha256sum "$ARCHIVE_NAME" > "$ARCHIVE_SUM"

            du -h "${ARCHIVE_NAME}"
            tar tzf "${ARCHIVE_NAME}"

            # To speed up the file sync back
            rm -rf "build/"
      - name: Upload archive
        if: env.CHECK == 'success'
        run: gh release upload "${{ needs.release.outputs.version }}" "${{ env.ARCHIVE_NAME }}" "${{ env.ARCHIVE_SUM }}"
        working-directory: archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
